# Generated by Django 2.0.4 on 2018-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gpic',
            field=models.ImageField(upload_to='df_goods/uploadpics'),
        ),
    ]
