# Generated by Django 2.0.4 on 2018-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20180420_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gpic',
            field=models.ImageField(height_field=180, upload_to='df_goods', width_field=180),
        ),
    ]
