# Generated by Django 2.0.4 on 2018-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20180426_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gpic',
            field=models.ImageField(upload_to='df_goods'),
        ),
    ]
